# Generated by Django 5.0.6 on 2024-07-08 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("clienteID", models.AutoField(primary_key=True, serialize=False)),
                ("nombres", models.CharField(max_length=255)),
                ("apellidos", models.CharField(max_length=255)),
                ("nit", models.CharField(max_length=20)),
                ("telefono", models.CharField(max_length=8)),
                ("email", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lugar",
            fields=[
                ("lugarID", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("minPersonas", models.IntegerField()),
                ("maxPersonas", models.IntegerField()),
                ("ubicacion", models.CharField(max_length=255)),
                ("detalles", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ServiciosOpcionales",
            fields=[
                ("servOpID", models.AutoField(primary_key=True, serialize=False)),
                ("servicio", models.CharField(max_length=255)),
                (
                    "precioUnitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("detalles", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("eventoID", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=255)),
                ("fecha", models.DateField()),
                ("horaInicio", models.TimeField()),
                ("horaFin", models.TimeField()),
                ("isCotizacion", models.BooleanField()),
                ("cantPersonas", models.IntegerField()),
                (
                    "clienteID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.cliente"
                    ),
                ),
                (
                    "lugarID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.lugar"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ListadoMenus",
            fields=[
                ("listMenuID", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.IntegerField()),
                ("observaciones", models.TextField()),
                (
                    "eventoID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.evento"
                    ),
                ),
                (
                    "menuID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.menu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiciosOpcionalesLista",
            fields=[
                ("servOpListID", models.AutoField(primary_key=True, serialize=False)),
                ("observaciones", models.TextField()),
                (
                    "eventoID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.evento"
                    ),
                ),
                (
                    "servOpID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gper.serviciosopcionales",
                    ),
                ),
            ],
        ),
    ]
