# Generated by Django 5.0.6 on 2024-07-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gper", "0002_cliente_lugar_serviciosopcionales_evento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cliente", old_name="clienteID", new_name="idCliente",
        ),
        migrations.RenameField(
            model_name="evento", old_name="eventoID", new_name="idEvento",
        ),
        migrations.RenameField(
            model_name="listadomenus", old_name="listMenuID", new_name="idListMenu",
        ),
        migrations.RenameField(
            model_name="lugar", old_name="lugarID", new_name="idLugar",
        ),
        migrations.RenameField(
            model_name="serviciosopcionales", old_name="servOpID", new_name="idServOp",
        ),
        migrations.RenameField(
            model_name="serviciosopcionaleslista",
            old_name="servOpListID",
            new_name="idServOpList",
        ),
    ]
