# Generated by Django 5.0.6 on 2024-07-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gper", "0003_rename_clienteid_cliente_idcliente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadmedida",
            name="unidad",
            field=models.CharField(
                error_messages="El campo no puede estar vacío", max_length=255
            ),
        ),
    ]
