# Generated by Django 5.0.6 on 2024-09-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gper", "0004_alter_unidadmedida_unidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingrediente",
            name="existencias",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
