# Generated by Django 5.0.6 on 2024-10-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gper", "0005_ingrediente_existencias"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnicasreceta",
            name="detalles",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
