# Generated by Django 5.0.6 on 2024-10-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gper", "0007_receta_procedimiento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="precioSugerido",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
