# Generated by Django 5.0.6 on 2024-10-28 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gper", "0008_receta_preciosugerido"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionUnidad",
            fields=[
                ("idConversion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "factorConversion",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Factor de conversión de origen a destino",
                        max_digits=10,
                    ),
                ),
                (
                    "unidadDestino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidad_destino",
                        to="gper.unidadmedida",
                    ),
                ),
                (
                    "unidadOrigen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidad_origen",
                        to="gper.unidadmedida",
                    ),
                ),
            ],
        ),
    ]
