# Generated by Django 5.0.6 on 2024-05-14 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                ("idIngrediente", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("unidadCompra", models.IntegerField()),
                (
                    "precioUnidadCompra",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("especificaciones", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("idMenu", models.AutoField(primary_key=True, serialize=False)),
                ("nombreOficial", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Origen",
            fields=[
                ("idOrigen", models.AutoField(primary_key=True, serialize=False)),
                ("origen", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TecnicaCoccion",
            fields=[
                (
                    "idTecnicaCoccion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                ("idUnidadMedida", models.AutoField(primary_key=True, serialize=False)),
                ("unidad", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Receta",
            fields=[
                ("idReceta", models.AutoField(primary_key=True, serialize=False)),
                ("codigoReceta", models.CharField(max_length=255)),
                ("nombreReceta", models.CharField(max_length=255)),
                ("noPorciones", models.IntegerField()),
                (
                    "temperaturaServicio",
                    models.CharField(
                        choices=[
                            ("frio", "Frio"),
                            ("caliente", "Caliente"),
                            ("al tiempo", "Al Tiempo"),
                        ],
                        default="caliente",
                        max_length=10,
                    ),
                ),
                ("tiempoElab", models.CharField(max_length=100)),
                ("costoReceta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precioVenta", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "idOrigen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.origen"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuRecetas",
            fields=[
                ("idMenuRecetas", models.AutoField(primary_key=True, serialize=False)),
                (
                    "menuId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.menu"
                    ),
                ),
                (
                    "recetaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.receta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientesReceta",
            fields=[
                (
                    "idIngredientesReceta",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("cantidadUso", models.IntegerField()),
                ("rendimiento", models.IntegerField()),
                (
                    "ingredienteId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gper.ingrediente",
                    ),
                ),
                (
                    "recetaID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.receta"
                    ),
                ),
                (
                    "medidaUso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gper.unidadmedida",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecetaCostos",
            fields=[
                ("idRecetaCostos", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ingredientesRecetaID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gper.ingredientesreceta",
                    ),
                ),
                (
                    "recetaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.receta"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TecnicasReceta",
            fields=[
                (
                    "idTecnicasReceta",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "recetaId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gper.receta"
                    ),
                ),
                (
                    "tecnicaID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gper.tecnicacoccion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ingrediente",
            name="idUnidadMedida",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gper.unidadmedida"
            ),
        ),
    ]
